Do not replay common init
OSAS/ansible-role-httpd pull request #38
Opened 2017-04-24 07:53 UTC by duck-rh

2017-04-24 12:22 UTC, mscherer requested changes
Also, please merge the 2 PR in 1. I spent 5 minutes to try to figure the order of the PR and where was the first one.

2017-04-24 12:22 UTC, mscherer commented on tasks/common.yml
> +    httpd_common: True
I would rather use a variable prefixed by _, to denote that's internal. Current code base is a bit inconsistant with that, but I rather not augment entropy.

2017-04-24 14:41 UTC, mscherer commented
Ok, I mean the 2 commits, sorry

2017-04-25 03:51 UTC, duck-rh commented
Let me know if you see more improvements you would like

2017-04-28 09:36 UTC, mscherer commented
So I would be ok to merge this, but I now realize that I do not understand the problem it is supposed to fix. 
(also, I think maybe ansible upstreal should support something to include a file only once, like it does for the dependencies )

2017-04-28 09:37 UTC, mscherer approved these changes

2017-04-30 05:36 UTC, duck-rh commented
I just extended whet you already started yourself. The goal is to avoid repeating rules we are sure were applied and make it faster.

Upstream support would be nice but sometimes you really want to replay them because you know something has changed, like when you want to change httpd server-level config as suggested in #36

2017-04-30 05:37 UTC, duck-rh commented
I'm gonna merge and we can re-discuss this later. At the moment it follows the role's logic and works.

2017-04-30 05:37 UTC, merged