Rename python wsgi
OSAS/ansible-role-httpd pull request #39
Opened 2017-04-24 07:54 UTC by duck-rh

depends on #38

2017-04-28 09:21 UTC, mscherer requested changes

2017-04-28 09:21 UTC, mscherer commented on tasks/common_wsgi.yml
> +    httpd_common_wsgi: True
There is a a '_' missing here, this break  the when condition later.

2017-04-30 05:44 UTC, duck-rh commented on tasks/common_wsgi.yml
> +    httpd_common_wsgi: True
my bad, thanks

2017-05-12 10:04 UTC, duck-rh commented
I fixed the mistake, anything else to improve?

2017-05-15 04:08 UTC, merged