Reindent the whole role
OSAS/ansible-role-httpd pull request #5
Opened 2016-10-11 13:32 UTC by mscherer

Also fix a few bugs:
- wrong permission on documentroot
- spurious conditional for enabling mod_security

2016-10-17 06:46 UTC, duck-rh requested changes
well, quite a boring rework I suppose, but really makes things much more readable

2016-10-17 06:46 UTC, duck-rh commented on tasks/freeipa.yml
> +    dest: /etc/pki/tls/certs/{{ _website_domain }}.ca.crt
I think it's better to add quotes whenever you use variables

2016-10-17 06:46 UTC, duck-rh commented on tasks/freeipa.yml
> +    dest: /etc/pki/tls/certs/{{ _website_domain }}.ca.crt
s/better/safest/

2016-10-17 06:46 UTC, duck-rh commented on tasks/main.yml
> +    dest: /etc/httpd/conf.d/{{ _website_domain }}.conf
same

2016-10-17 06:46 UTC, duck-rh commented on tasks/main.yml
> +    dest: /etc/httpd/conf.d/{{ _website_domain }}_ssl.conf
same

2016-10-17 06:46 UTC, duck-rh commented on tasks/main.yml
> +  name: Clean force_tls and use_tls
putting the name before would improve readability

2016-10-17 06:46 UTC, duck-rh commented on tasks/mod_security.yml
> -  when: mod_sec_detection_only is True
side-effect change I suppose

2016-10-17 06:46 UTC, duck-rh commented on tasks/password_present.yml
> +    path: /etc/httpd/{{ _website_domain }}.htpasswd
same

2016-10-17 06:46 UTC, duck-rh commented on tasks/password_present.yml
> +  no_log: True
good catch but outside this PR

2016-10-17 06:46 UTC, duck-rh commented on tasks/redirect.yml
> +    dest: /etc/httpd/conf.d/{{ _website_domain }}.conf.d/redirect.conf
same

2016-10-17 06:46 UTC, duck-rh commented on tasks/redirect_to_https.yml
> +    dest: /etc/httpd/conf.d/{{ _website_domain }}.conf.d/redirect_to_https.conf
same

2016-10-17 06:46 UTC, duck-rh commented on tasks/redirects.yml
> +    dest: /etc/httpd/conf.d/{{ _website_domain }}.conf.d/redirects.conf
same

2016-10-17 06:46 UTC, duck-rh commented on tasks/reverse_proxy.yml
> +    dest: /etc/httpd/conf.d/{{ _website_domain }}.conf.d/reverse_proxy.conf
same

2016-10-17 06:46 UTC, duck-rh commented on tasks/server_alias.yml
> +    dest: /etc/httpd/conf.d/{{ _website_domain }}.conf.d/server_alias.conf
same

2016-10-21 12:53 UTC, mscherer commented on tasks/mod_security.yml
> -  when: mod_sec_detection_only is True
that's written in the PR: "spurious conditional for enabling mod_security".

2016-10-24 03:55 UTC, duck-rh commented on tasks/mod_security.yml
> -  when: mod_sec_detection_only is True
true, missed reading the description. nevertheless it should be in a separate PR, or in a patchset PR so you can review each part individually

2016-10-24 03:58 UTC, merged