Do not declare WSGIDaemonProcess in a vhost
OSAS/ansible-role-httpd pull request #7
Opened 2016-10-24 05:44 UTC by mscherer

Since it cannot be declared more than once, we need to have it declared
once per domain, and if possible outside of the conf.d/$DOMAIN.conf.d/
directory, since this would cause conflict with http and https
hosts as found out by Duck.

2016-10-24 16:15 UTC, duck-rh requested changes
the idea is good, but only works if we happen to have only one such WSGI script. Happily we used the combined WSGI daemon make by abompard for MM3, but it could have been two. Also for the principle of least surprise we should document or handle it.

We could name the file _website_domain_wsgi_daemon.conf to solve this problem.

2016-10-25 10:42 UTC, mscherer commented
Yeah, I figured the same when submitting. I will fix after my PTO and openstack summit.

2016-10-25 12:30 UTC, mscherer commented
In fact, I suspect the right fix is to push that in vhost.conf.

2016-10-25 16:42 UTC, duck-rh commented
it would indeed avoid having many files which would then need to be deleted when the feature is disabled. Let's do this.

2016-10-25 23:13 UTC, mscherer commented
The fact is indeed, the .config.d is for composing with external roles, and since that's internal setup, we can avoid. That make it more complex, but complexity in different files or in template is still complexity.

I am not sure if "removing files" is a concern for most setup (like, I do not imagine use removing mailman 3 from 1 server, even if I imagine us removing password protection, and others stuff), so while that's a concern, that's not a big one. In a ideal world of immutable server, that problem should solve itself. But we are not hear yet, and will not be here soon.

2016-10-26 03:33 UTC, duck-rh commented
it's true a server often does not change "role", but it's a concern when we redesign a role and obsolete a config file or reorganize. I may be wrong but I think we already hit the situation in some role.

Anyway, I said I agree with the solution, so we can go on.

2016-12-02 06:58 UTC, duck-rh commented
I could do the changes if you're busy, as we agreed on a solution.

2017-04-25 03:42 UTC, duck-rh commented
I reread the doc and WSGIScriptAlias needs either a process-group parameter which is referenced in the WSGIDaemonProcess page but not the WSGIScriptAlias one. So the WSGIProcessGroup declaration needs to be along the WSGIScriptAlias declaration to choose which one to use in order to support multiple WSGI instances.

So I would keep the idea of this PR and experiment to declare a global (outside vhost) daemon and select it on both HTTP and HTTPS vhosts, which could solve the inclusion problem.

This PR was stall for some time so I plan to plan on this in a new one.

2017-04-25 04:25 UTC, duck-rh commented
So the goal would be to work on it once #36 is settled, quickly, so as not to use it in production yet, and avoid handling legacy config files to remove. As I'm the only one yet using WSGI I should be able to manage that.

2017-05-15 04:41 UTC, duck-rh commented
implemented in branch 'duck_work_during_misc_vacation' at the moment. I will create a new PR after #36 is settled with @mscherer

2017-05-15 04:41 UTC, closed without merging